export const calendarDays = [
  {
    "id": 0,
    "day_index": 1,
    "day_has_started": true,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Edward Scissorhands",
    "product_name": "Edward Scissorhands",
    "product_url": "https://www.hulu.com/movie/edward-scissorhands-c71d11de-32df-4fb5-a0f1-06e1e0a0d5aa",
  },
  {
    "id": 1,
    "day_index": 2,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Corpse Bride",
    "product_name": "Corpse Bride",
    "product_url": "https://www.amazon.com/Burtons-Corpse-Bride-Johnny-Depp/dp/B000GOWSF0",
  },
  {
    "id": 2,
    "day_index": 3,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Casper",
    "product_name": "Casper",
    "product_url": "https://www.amazon.com/Casper-Christina-Ricci/dp/B000I9S5SC",
  },
  {
    "id": 3,
    "day_index": 4,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Ghost",
    "product_name": "Ghost",
    "product_url": "https://www.netflix.com/title/60010395?source=35",
  },
  {
    "id": 4,
    "day_index": 5,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Frankenweenie",
    "product_name": "Frankenweenie",
    "product_url": "https://www.amazon.com/Frankenweenie-Charlie-Tahan/dp/B00AOOHIJS",
  },
  {
    "id": 5,
    "day_index": 6,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Young Frankenstein",
    "product_name": "Young Frankenstein",
    "product_url": "https://www.amazon.com/Young-Frankenstein-Gene-Wilder/dp/B07BGRW4VN",
  },
  {
    "id": 6,
    "day_index": 7,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Beetlejuice",
    "product_name": "Beetlejuice",
    "product_url": "https://www.amazon.com/Beetlejuice-Michael-Keaton/dp/B001EC2ISA",
  },
  {
    "id": 7,
    "day_index": 8,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Monsters Inc",
    "product_name": "Monsters Inc",
    "product_url": "https://www.amazon.com/Monsters-Inc-John-Goodman/dp/B0049J2BSM",
  },
  {
    "id": 8,
    "day_index": 9,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster The Curse of the Were Rabbit",
    "product_name": "The Curse of the Were Rabbit",
    "product_url": "https://www.amazon.com/Wallace-Gromit-Were-Rabbit-Nick-Parker/dp/B079HSNWZ5/",
  },
  {
    "id": 9,
    "day_index": 10,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster The Craft",
    "product_name": "The Craft",
    "product_url": "https://www.amazon.com/Craft-Robin-Tunney/dp/B000MQ7B0O",
  },
  {
    "id": 10,
    "day_index": 11,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Practical Magic",
    "product_name": "Practical Magic",
    "product_url": "https://www.amazon.com/Practical-Magic-Sandra-Bullock/dp/B000GOLTTQ",
  },
  {
    "id": 11,
    "day_index": 12,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Goosebumps",
    "product_name": "Goosebumps",
    "product_url": "https://www.amazon.com/Goosebumps-Jack-Black/dp/B016Q1LRPI",
  },
  {
    "id": 12,
    "day_index": 13,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Only Lovers Left Alive",
    "product_name": "Only Lovers Left Alive",
    "product_url": "https://www.amazon.com/Only-Lovers-Left-Alive-John/dp/B00LD6TKOM",
  },
  {
    "id": 13,
    "day_index": 14,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Addams Family Values",
    "product_name": "Addams Family Values",
    "product_url": "https://www.amazon.com/Addams-Family-Values-Christopher-Lloyd/dp/B002PSXS54",
  },
  {
    "id": 14,
    "day_index": 15,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Gremlins",
    "product_name": "Gremlins",
    "product_url": "https://www.amazon.com/Gremlins-Zach-Galligan/dp/B00KQ9UTSI",
  },
  {
    "id": 15,
    "day_index": 16,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster The Addams Family",
    "product_name": "The Addams Family (2019)",
    "product_url": "https://www.amazon.com/Addams-Family-Chlo%C3%AB-Grace-Moretz/dp/B07YX15ZT9",
  },
  {
    "id": 16,
    "day_index": 17,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Paranorman",
    "product_name": "Paranorman",
    "product_url": "https://www.netflix.com/title/70217914",
  },
  {
    "id": 17,
    "day_index": 18,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "Movie poster Hocus Pocus",
    "product_name": "Hocus Pocus",
    "product_url": "https://www.amazon.com/Hocus-Pocus-Bette-Midler/dp/B004JMY312",
  },
  {
    "id": 18,
    "day_index": 19,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "TV show poster Buffy the Vampire Slayer",
    "product_name": "Buffy the Vampire Slayer",
    "product_url": "https://www.amazon.com/Buffy-Vampire-Slayer-Season-1/dp/B000HCYN18",
  },
  {
    "id": 19,
    "day_index": 20,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "TV show poster The Simpsons: Treehouse of Horror",
    "product_name": "The Simpsons: Treehouse of Horror",
    "product_url": "https://www.amazon.com/Simpsons-Treehouse-Horror-Season/dp/B009NB7DYI",
  },
  {
    "id": 20,
    "day_index": 21,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "TV show poster Sabrina the Teenage Witch",
    "product_name": "Sabrina the Teenage Witch",
    "product_url": "https://www.hulu.com/series/sabrina-the-teenage-witch-502bbc34-fa19-48fb-89c6-074da28335d3",
  },
  {
    "id": 21,
    "day_index": 22,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "TV show poster The Curious Creations of Christine McConnell",
    "product_name": "The Curious Creations of Christine McConnell",
    "product_url": "https://www.netflix.com/title/80201868",
  },
  {
    "id": 22,
    "day_index": 23,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "TV show poster Are You Afraid of the Dark?",
    "product_name": "Are You Afraid of the Dark?",
    "product_url": "https://www.netflix.com/title/81486551",
  },
  {
    "id": 23,
    "day_index": 24,
    "day_has_started": false,
    "day_checked": false,
    "image_file_path": "https://via.placeholder.com/150",
    "image_alt_text": "The show poster The Chilling Adventures of Sabrina",
    "product_name": "The Chilling Adventures of Sabrina",
    "product_url": "https://www.netflix.com/title/80223989",
  }
]